[project]
name = "pytechnitiumapi"
version = "0.1.0"
description = ""
authors = [
    {name = "Quien Sabe",email = "qs5778@mail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "api-client-framework (>=0.1.0,<0.2.0)"
]

[project.urls]
homepage = "https://github.com/wtfo-guru/pytechnitiumapi"
documentation = "https://sterces.readthedocs.io/en/pytechnitiumapi"

[tool.poetry]
packages = [{include = "pytechnitiumapi", from = "src"}]

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
mypy = "^1.17.0"
wemake-python-styleguide = "^1.0"
flake8-pytest-style = "^2.0"
doc8 = "^2.0"
docutils = "^0.21.2"
pytest = "^9.0"
pytest-cov = "^7.0"
isort = "^8.0"
black = "^26.0"
darglint = "^1.8.1"
flake8-docstrings = "^1.7.0"
flake8-rst-docstrings = "^0.3.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^8.0"
sphinx-autodoc-typehints = "^3.0"
tomli = "^2.2.1"
sphinx-mdinclude = "^0.6.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.nitpick]
style = "https://www.wtfo-guru.com/.well-known/nitpick-wtf-style.toml"
